<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuiteDataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>db64ec0c-1a2c-45bc-9773-c3c079d8399a</testSuiteGuid>
   <testCaseLink>
      <guid>27b1018a-bb36-4f0d-9c18-0a097d6f0181</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTest/TestCaseDataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>61d8817c-c308-4f0f-bbf9-7e7c4d1b0f7a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>61d8817c-c308-4f0f-bbf9-7e7c4d1b0f7a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>be06a770-bcfc-4cb5-91bc-9e8d36f70ac0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>61d8817c-c308-4f0f-bbf9-7e7c4d1b0f7a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>f75194b1-4fcb-43f1-9b18-2c8c536864b5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
