<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Make the rest of your life the best of your life</name>
   <tag></tag>
   <elementGuidId>12eaabf7-3fb3-4908-8474-175ee14c750d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-1528']/header/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3667206d-8542-4962-ac2d-b032cf94d198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://lifecharger.org/make-the-rest-of-your-life-the-best-of-your-life/</value>
      <webElementGuid>fb468987-8235-4b2f-bfb4-a46556a7c22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Make the rest of your life the best of your life</value>
      <webElementGuid>2c54d739-c3db-4025-9d6d-09a475225231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1528&quot;)/header[@class=&quot;entry-header&quot;]/h2[1]/a[1]</value>
      <webElementGuid>e34d1ec9-4e5d-404b-879d-a986e3e1b8c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-1528']/header/h2/a</value>
      <webElementGuid>7c0ad95d-e7c1-4ee5-86fb-0287a2b6e360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Make the rest of your life the best of your life')]</value>
      <webElementGuid>a873bfc0-96f8-444f-a17b-e1d81edf7ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/following::a[2]</value>
      <webElementGuid>13410662-14ca-4dfd-9c53-18bba7f0091a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Books I am reading…'])[1]/following::a[3]</value>
      <webElementGuid>84b50968-5c74-4e33-a326-51214f71d6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nothing will move unless you do'])[1]/preceding::a[1]</value>
      <webElementGuid>684329e5-2234-4392-a1d8-673aadad1fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='It’s so easy and simple, let me just get this done'])[1]/preceding::a[1]</value>
      <webElementGuid>70aa4708-db88-4694-8171-a85ffd5485d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Make the rest of your life the best of your life']/parent::*</value>
      <webElementGuid>e014680c-ca38-4616-996f-9e3726cf7dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://lifecharger.org/make-the-rest-of-your-life-the-best-of-your-life/')]</value>
      <webElementGuid>157bdb0e-c8ed-468a-abe5-6dce2b338624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>d8fe0625-02fa-42c5-8c30-7d8dc7a71044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://lifecharger.org/make-the-rest-of-your-life-the-best-of-your-life/' and (text() = 'Make the rest of your life the best of your life' or . = 'Make the rest of your life the best of your life')]</value>
      <webElementGuid>88e00329-eed3-4aab-9eda-feeb4cdd098f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
